#!/usr/bin/env bash
set -euo pipefail

# Resolve script home
SOURCE="${BASH_SOURCE[0]}"
# resolve $SOURCE until the file is no longer a symlink
while [ -h "$SOURCE" ]; do
  SCRIPT_HOME="$( cd -P "$( dirname "$SOURCE" )" >/dev/null && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
  [[ $SOURCE != /* ]] && SOURCE="$SCRIPT_HOME/$SOURCE"
done
SCRIPT_HOME="$( cd -P "$( dirname "$SOURCE" )" >/dev/null && pwd )"


. "$SCRIPT_HOME/../common"

GENERATED_MARKER="<!-- Generated by apply-to-codex.sh; do not edit directly. -->"

function with_codex_guidance_lock() {
  local lock_dir="${1:?lock dir is required}"
  shift
  local status=0

  local attempts=0
  until mkdir "${lock_dir}" 2>/dev/null; do
    attempts=$((attempts + 1))
    if (( attempts >= 50 )); then
      echo "failed to acquire lock: ${lock_dir}" >&2
      return 1
    fi
    sleep 0.1
  done

  "$@" || status=$?
  rmdir "${lock_dir}"
  return "${status}"
}

function ensure_generated_target() {
  local target_file="${1:?target file is required}"
  local guidance_home="${2:?guidance home is required}"

  if [[ ! -e "${target_file}" && ! -L "${target_file}" ]]; then
    return
  fi

  if [[ -L "${target_file}" ]]; then
    local target_link
    local item

    target_link="$(readlink "${target_file}")"
    for item in "${guidance_home}"/*.md; do
      [[ -L "${item}" ]] || continue
      if [[ "$(readlink "${item}")" == "${target_link}" ]]; then
        echo "-- Replacing legacy Codex guidance symlink ${target_file}"
        rm "${target_file}"
        return
      fi
    done

    echo "refusing to replace symlink: ${target_file}" >&2
    return 1
  fi

  if [[ "$(head -n 1 "${target_file}")" != "${GENERATED_MARKER}" ]]; then
    echo "refusing to replace non-generated file: ${target_file}" >&2
    return 1
  fi
}

function rebuild_codex_guidance() {
  local guidance_home="${1:?guidance home is required}"
  local target_file="${2:?target file is required}"
  local target_dir
  local tmp_file

  target_dir="$(dirname -- "${target_file}")"
  mkdir -p "${target_dir}"
  ensure_generated_target "${target_file}" "${guidance_home}"
  tmp_file="$(mktemp "${target_dir}/.$(basename -- "${target_file}").tmp.XXXXXX")"
  {
    echo "${GENERATED_MARKER}"
    echo "<!-- Source fragments: ${guidance_home}/*.md -->"
    local item
    for item in "${guidance_home}"/*.md; do
      if [[ -L "${item}" && ! -e "${item}" ]]; then
        echo "warning: skipping broken guidance symlink: ${item}" >&2
        continue
      fi
      [[ -f "${item}" ]] || continue
      echo ""
      echo "<!-- BEGIN $(basename -- "${item}") -->"
      cat -- "${item}"
      echo ""
      echo "<!-- END $(basename -- "${item}") -->"
    done
  } > "${tmp_file}" || {
    rm -f "${tmp_file}"
    return 1
  }

  mv -f "${tmp_file}" "${target_file}" || {
    rm -f "${tmp_file}"
    return 1
  }
}

function register_and_rebuild_codex_guidance() {
  local source_file="${1:?source file is required}"
  local guidance_file="${2:?guidance file is required}"
  local guidance_home="${3:?guidance home is required}"
  local codex_agents_file="${4:?codex agents file is required}"
  local legacy_guidance_file="${5:-}"

  if [[ -n "${legacy_guidance_file}" && "${legacy_guidance_file}" != "${guidance_file}" ]]; then
    if [[ -L "${legacy_guidance_file}" && "$(readlink "${legacy_guidance_file}")" == "${source_file}" ]]; then
      echo "-- Removing legacy guidance fragment ${legacy_guidance_file}"
      rm "${legacy_guidance_file}"
    elif [[ -e "${legacy_guidance_file}" || -L "${legacy_guidance_file}" ]]; then
      echo "refusing to replace legacy guidance fragment: ${legacy_guidance_file}" >&2
      return 1
    fi
  fi

  if [[ -e "${guidance_file}" || -L "${guidance_file}" ]]; then
    if [[ ! -L "${guidance_file}" || "$(readlink "${guidance_file}")" != "${source_file}" ]]; then
      echo "guidance fragment name conflict: ${guidance_file}" >&2
      return 1
    fi
  else
    link "${source_file}" "${guidance_file}"
  fi

  rebuild_codex_guidance "${guidance_home}" "${codex_agents_file}"
}

function main() {
  local agents_home="${HOME}/.agents"
  local guidance_home="${agents_home}/agents.d"
  local codex_home="${CODEX_HOME:-${HOME}/.codex}"

  # Create ~/.agents if not exists
  if [[ ! -d "${agents_home}" ]]; then
    echo "-- Creating ${agents_home}"
    mkdir -p "${agents_home}"
  fi

  # Create Codex home if not exists
  if [[ ! -d "${codex_home}" ]]; then
    echo "-- Creating ${codex_home}"
    mkdir -p "${codex_home}"
  fi

  # Register global guidance and rebuild Codex's always-loaded file
  if [[ -f "${SCRIPT_HOME}/AGENTS.global.md" ]]; then
    if [[ ! -d "${guidance_home}" ]]; then
      echo "-- Creating ${guidance_home}"
      mkdir -p "${guidance_home}"
    fi
    with_codex_guidance_lock "${agents_home}/.codex-guidance.lock" \
      register_and_rebuild_codex_guidance \
      "${SCRIPT_HOME}/AGENTS.global.md" \
      "${guidance_home}/setup-base.md" \
      "${guidance_home}" \
      "${codex_home}/AGENTS.md" \
      "${guidance_home}/10-setup-base.md"
  fi

  # Link skills individually
  if [[ -d "${SCRIPT_HOME}/skills" ]]; then
    if [[ ! -d "${agents_home}/skills" ]]; then
      echo "-- Creating ${agents_home}/skills"
      mkdir -p "${agents_home}/skills"
    fi
    for item in "${SCRIPT_HOME}/skills"/*; do
      [[ -d "${item}" ]] || continue
      local name
      name=$(basename "${item}")
      link "${item}" "${agents_home}/skills/${name}"
    done
  fi

}

main "$@"
