#Priorit: prefix key and reloading tmux.conf:
#-------------------------------------------------------#
# change prefix from C-b to C-a
unbind C-b
set -g prefix C-a

# bind C-a C-a to 'home', or start of line, which was C-a previously
bind C-a send-prefix

#Terminal admin:
#-------------------------------------------------------#
# set mouse off/on - if off, forces you to use keyboard with prefix-[
set -g mouse on

# tmux-256color: better support for italic, undercurl, etc. than screen-256color
set -g default-terminal "tmux-256color"

# extend history limit
set -g history-limit 50000

# start with window 1 (instead of 0)
set -g base-index 1

# start with pane 1
set -g pane-base-index 1

# alt + w + n for new window
bind-key -T split_table n   new-window
bind-key -T split_table M-n new-window

# alt + w + w for session selection
bind-key -T split_table w   choose-tree -s
bind-key -T split_table M-w choose-tree -s

# pane split
bind-key v split-window -h
bind-key s split-window -v

# alt + w + hjkl for splitting
bind-key -n M-w switch-client -T split_table
bind-key -T split_table h   split-window -hb
bind-key -T split_table M-h split-window -hb
bind-key -T split_table l   split-window -h
bind-key -T split_table M-l split-window -h
bind-key -T split_table k   split-window -vb
bind-key -T split_table M-k split-window -vb
bind-key -T split_table j   split-window -v
bind-key -T split_table M-j split-window -v

# vim style pane selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# alt + hjkl
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# window selection
# alt + 1, 2, 3, ...
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5

# window cycle selection
# alt + n, p
bind -n M-n next-window
bind -n M-p previous-window

# monitor activity/silence
setw -g monitor-activity on
set -g visual-activity on
# usage: manually enable silence monitoring on a specific window
#   prefix + : → setw monitor-silence 30

# theme
set -g status-bg black
set -g status-fg white
set -g status-interval 60
set -g status-left-length 30

# https://github.com/tmux/tmux/issues/1689
set -g mode-style bg=white,fg=black,bold  # bold not work.. why?
